#!/bin/sh

VERSION="1.3"
REV=`git rev-list --count HEAD`
DIR="clunk-${VERSION}.${REV}"
echo "exporting clunk to ${DIR}"
pushd ..
git archive --format zip --prefix "${DIR}/" --output contrib/${DIR}.zip master
git archive --format tar --prefix "${DIR}/" --output contrib/${DIR}.tar master
bzip2 contrib/${DIR}.tar
popd
