/*
MIT License

Copyright (c) 2008-2019 Netive Media Group & Vladimir Menshakov

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#ifndef CLUNK_KEMAR_H
#define CLUNK_KEMAR_H

/*
This data is Copyright 1994 by the MIT Media Laboratory. 
It is provided free with no restrictions on use, 
provided the authors are cited when the data is used in any research or commercial application.

Bill Gardner billg@media.mit.edu and Keith Martin kdm@media.mit.edu
*/

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DO NOT EDIT THIS HEADER, IT'S AUTOGENERATED */
static const int KemarMinElevation = -40;
static const int KemarMaxElevation = 90;
static const int KemarElevationCount = 14;
static const int KemarElevationStep = 10;
static const unsigned KemarPoints = 513;

struct kemar_elevation_data {
	int elevation;
	unsigned samples;
	const float (*data)[2][513][2];
};

extern struct kemar_elevation_data kemar_data[14];

#ifdef __cplusplus
}
#endif

#endif
